library(readxl)
diabetest1 <- read_excel("C:\\Users\\Reddy\\Documents\\NARA.xlsx")
A <- c(diabetest1$Age)
Mean <- mean(A, na.rm = TRUE)
Minimum <- min(A, na.rm = TRUE)
Maximum <- max(A, na.rm = TRUE)
print(Mean)
print(Minimum)
print(Maximum)